enum actionTypeKeys {
	GET_LISTS = "GET_LISTS",
	GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS",
	ADD_CARD = "ADD_CARD",
	ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS",
	ADD_LIST = "ADD_LIST",
	ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS",
	DRAG_HAPPENED = "DRAG_HAPPENED",
}

export default actionTypeKeys;
